name: CI/CD Spring Boot Docker

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/absm-be-deploy

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          FULL_IMAGE="${IMAGE_NAME}:${GITHUB_SHA}"
          echo "full_image=$FULL_IMAGE" >> $GITHUB_OUTPUT
          docker build --file Dockerfile \
            --tag "$FULL_IMAGE" \
            --tag "${IMAGE_NAME}:latest" \
            .
          docker push "$FULL_IMAGE"
          docker push "${IMAGE_NAME}:latest"
